{% set version = "1.3.5" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-domc
  version: {{ version|replace("-", "_") }}

source:
  fn: doMC_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/doMC_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/doMC/doMC_{{ version }}.tar.gz
  sha256: 792254596babd8cc074bb3c83c18672dd07a0c3246b4ebab08d8ebedf6f4d9ed

build:
  number: 0
  # Unix only package
  skip: true  # [win]

  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - r-base
    - r-foreach >=1.2.0
    - r-iterators >=1.0.0

  run:
    - r-base
    - r-foreach >=1.2.0
    - r-iterators >=1.0.0

test:
  commands:
    - $R -e "library('doMC')"  # [not win]
    - "\"%R%\" -e \"library('doMC')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=doMC
  license: GPL-2
  summary: Provides a parallel backend for the %dopar% function using the multicore functionality
    of the parallel package.
  license_family: GPL2

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
