appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: srM3RiQh62f2Bb8qMyF9EvhloA34GUD7jxTUGdMvQQTyIOwtG8RwdEDoJbwmxM/XotbHSRYCvStstzBNaYdR0PEQtd4Z25UfYzcCiwsNmvCbtuEhTZKuN4Sw+zAQBILzzoTRUjI0JSJcRG1cdvkTVhSj/KfYy227m7Vm3M0PSvYbhvNkqeOGY7VFjyfqneA7+xJib/n3/6HgYdOu9OMXoAJxz6X58WqiA1ghcS7PQYRQ3PBpAme+Cw7A/8qxFzM6y9v33VLO/d5pNqqY+hp/+sVstvagw0kx1xvLtanjvVtRyMU8J/xWTKM7mWpHcnvQtwDfVuH1JqH/PPXXoknkKXhpdWz945lXaQLHcKUEshG1MIw/SI2WCtrUymJsNUtk1wFh3JuL6u1WzsCmuQ+SKVXwPs0mk93y0RC/UXw7gNKvd5zpr5SkUqBn28np0abiI3TqCA5kk18M1xpDgplDMBgeDDj/cZYZ2htBFCEh/EBY45nyqqgfz8m2skvCvvA+UKKlqKmfoeu9o0HRuI+OaI55MfihszXfPynDLQnnAqtYS3jMB4VdlxdR8+xu29IqcW0BdsDdZnOEtQYwSinl0O7ZLbiaKMefwPwgSINZnIQXuJMkVyI4egWks4IC8Iun+4PE72klsFw/J+K3AS+FCn5aY35B8Dw9L6/JECbOWJw=}
